### ISSUE TITLE
Preference files should be sorted

### ISSUE THREAD

**Issue by lukelast** [veithen/eclipse-settings-maven-plugin#1]
Please lexicographically sort the Eclipse preference files, otherwise every change results in a diff disaster.

**Comment by veithen** [comment]
Can you provide more information about your use case? You'd get a diff disaster only if you add the settings file in source control, but that's not how I use (and designed) the plugin: the idea is that the entire Eclipse configuration should be derived from the Maven configuration (either by M2E or this plugin).

**Comment by lukelast** [comment]
Right, since this plugin allows adding lines instead of replacing the whole file, if the result was sorted it would open up the use case of a slow migration to using this plugin on files already in git.
I'm interested in in trying it out slowly. I don't think sorting would have any downside.

Also when you are generating the entire .pref file, how often do you run it?
If the .pref files aren't in git I'd be worried about how to detect changes. Eclipse loves to make changes, especially when new versions come out.

**Comment by veithen** [comment]
> Right, since this plugin allows adding lines instead of replacing the whole file, if the result was sorted it would open up the use case of a slow migration to using this plugin on files already in git.
I'm interested in in trying it out slowly. I don't think sorting would have any downside.

That makes sense. The best solution would actually be to use the Eclipse code to manipulate those files. I looked into this when I wrote the original code, but didn't go down that route because it looks like there is a fair amount of machinery to initialize to use the relevant Eclipse APIs. I might give that another try though.

> Also when you are generating the entire .pref file, how often do you run it?
If the .pref files aren't in git I'd be worried about how to detect changes. Eclipse loves to make changes, especially when new versions come out.

The settings will be updated when running Maven from the command line (The mojo is bound to the `initialize` phase, so it will be executed by any build) and when updating the Maven project in Eclipse.

**Comment by lukelast** [comment]
Ah, running on "maven update project" makes sense.

I agree that using the Eclipse code would ensure the output is the same, but a simple sort might achieve the same results, based on my glancing at some .pref files.

Thanks for looking at it.
